### ISSUE TITLE
How to remap vol up / vol down keys?

### ISSUE THREAD

**Issue by UksusoFF** [PolarGoose/AutoHotKey-Natural-Ergonomic-Keyboard-4000-support#3]
Thanks for this wonderful tool! 

Can you tell how to get codes for this buttons?
![image](https://user-images.githubusercontent.com/1931442/76831636-20c27800-6841-11ea-8dbe-0c6031dae17e.png)

**Comment by PolarGoose** [comment]
Volume Up/Down buttons are standard buttons and are supported from the box without needing to use my library. More information can be found here: https://www.autohotkey.com/docs/KeyList.htm#multimedia
For example, you can do it like this:
```
Volume_Up::
    MsgBox volume up button is pressed
    return

Volume_Down::
    MsgBox volume down button is pressed
    return
```

**Comment by UksusoFF** [comment]
Okay. But I want remap only this keys but save Vol Up/Down from Zoom Up/Down.
```
DoScroll:
    if (ScrollDir = 1)
        SendInput, {Volume_Up}
    else
        SendInput, {Volume_Down}
    return
```
Your upper example will change Zoom behavior too.

**Comment by PolarGoose** [comment]
@UksusoFF, the "DoScroll" code sample you have provided is different from my "example.ahk" code:
https://github.com/PolarGoose/AutoHotKey-Natural-Ergonomic-Keyboard-4000-support/blob/master/example.ahk#L11
the "example.ahk" uses `WheelUp` and `WheelDown` keys, not `Volume_Up`/`Volume_Down`.
Therefore, if you remap `Volume_Up`/`Volume_Down` keys, it won't affect scrolling functionality.

**Comment by PolarGoose** [comment]
@UksusoFF, Am I right that you want Zoom buttons to change sound volume? And you want volume up/down buttons to do something else?

**Comment by UksusoFF** [comment]
@PolarGoose yes. It's right.

**Comment by PolarGoose** [comment]
try to use `SoundSet` function ( https://www.autohotkey.com/docs/commands/SoundSet.htm ) in your "DoScroll" instead of Volume_Up/Volume_Down. For example:
```
DoScroll:
    if (ScrollDir = 1)
        SoundSet +10  ; Increase master volume by 10%
    else
        SoundSet -10  ; Decrease master volume by 10%
    return
```
then you will be able to safely remap Volume_Up/Volume_Down buttons.

**Comment by UksusoFF** [comment]
This works. But not show volume level:
![image](https://user-images.githubusercontent.com/1931442/77158053-fb8d6e00-6abb-11ea-8c34-6701b15c03a5.png)

Volume buttons can't be remapped with key codes?

**Comment by PolarGoose** [comment]
> Volume buttons can't be remapped with key codes?

Unfortunately, It can't be done via key codes.

**Comment by UksusoFF** [comment]
Thanks. Damned Microsoft.
