### ISSUE TITLE
Requires AutoHotkey v1

### ISSUE THREAD

**Issue by daviddoria** [PolarGoose/AutoHotKey-Natural-Ergonomic-Keyboard-4000-support#8]
Is it a big chore to make this work with v2?

**Comment by PolarGoose** [comment]
Hello @daviddoria, thank you for the interest in my script.

* The script uses a [AHKHID](https://github.com/jleb/AHKHID) library which is not available for AutoHotkey2. Migrating this library to new AutoHotkey can be a serious challenge.
* Unfortunately I don't know much about how the AutoHotkey2 breaking changes will affect this library and my script, therefore I can't make an effort assessment.
* `Microsoft Natural Ergonomic Keyboard 4000` is deprecated and it is hard or unreasonable to buy a new one. There are much better alternative available on the market.

Therefore in my opinion it doesn't worth spending effort migrating this script to AutoHotkey2.
You can still run in parallel AutoHotkey v1 for this script and AutoHotkey v2 for your other scripts.

**Comment by daviddoria** [comment]
Thanks for the detailed explanation - will do!
